// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: weather.proto

package weatherpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Weather struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Timezone         string                 `protobuf:"bytes,1,opt,name=timezone,proto3" json:"timezone,omitempty"`
	TimeAbbreviation string                 `protobuf:"bytes,2,opt,name=time_abbreviation,json=timeAbbreviation,proto3" json:"time_abbreviation,omitempty"`
	Hourly           *Hourly                `protobuf:"bytes,3,opt,name=hourly,proto3" json:"hourly,omitempty"`
	HourlyUnits      *HourlyUnits           `protobuf:"bytes,4,opt,name=hourly_units,json=hourlyUnits,proto3" json:"hourly_units,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Weather) Reset() {
	*x = Weather{}
	mi := &file_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weather) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weather) ProtoMessage() {}

func (x *Weather) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weather.ProtoReflect.Descriptor instead.
func (*Weather) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{0}
}

func (x *Weather) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *Weather) GetTimeAbbreviation() string {
	if x != nil {
		return x.TimeAbbreviation
	}
	return ""
}

func (x *Weather) GetHourly() *Hourly {
	if x != nil {
		return x.Hourly
	}
	return nil
}

func (x *Weather) GetHourlyUnits() *HourlyUnits {
	if x != nil {
		return x.HourlyUnits
	}
	return nil
}

type Hourly struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Time           string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Temperature_2M float64                `protobuf:"fixed64,2,opt,name=temperature_2m,json=temperature2m,proto3" json:"temperature_2m,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Hourly) Reset() {
	*x = Hourly{}
	mi := &file_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hourly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hourly) ProtoMessage() {}

func (x *Hourly) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hourly.ProtoReflect.Descriptor instead.
func (*Hourly) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{1}
}

func (x *Hourly) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Hourly) GetTemperature_2M() float64 {
	if x != nil {
		return x.Temperature_2M
	}
	return 0
}

type HourlyUnits struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Temperature_2M string                 `protobuf:"bytes,2,opt,name=temperature_2m,json=temperature2m,proto3" json:"temperature_2m,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HourlyUnits) Reset() {
	*x = HourlyUnits{}
	mi := &file_weather_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HourlyUnits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HourlyUnits) ProtoMessage() {}

func (x *HourlyUnits) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HourlyUnits.ProtoReflect.Descriptor instead.
func (*HourlyUnits) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{2}
}

func (x *HourlyUnits) GetTemperature_2M() string {
	if x != nil {
		return x.Temperature_2M
	}
	return ""
}

var File_weather_proto protoreflect.FileDescriptor

const file_weather_proto_rawDesc = "" +
	"\n" +
	"\rweather.proto\"\xa5\x01\n" +
	"\aWeather\x12\x1a\n" +
	"\btimezone\x18\x01 \x01(\tR\btimezone\x12+\n" +
	"\x11time_abbreviation\x18\x02 \x01(\tR\x10timeAbbreviation\x12\x1f\n" +
	"\x06hourly\x18\x03 \x01(\v2\a.HourlyR\x06hourly\x120\n" +
	"\fhourly_units\x18\x04 \x01(\v2\r.Hourly_unitsR\vhourlyUnits\"C\n" +
	"\x06Hourly\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12%\n" +
	"\x0etemperature_2m\x18\x02 \x01(\x01R\rtemperature2m\"5\n" +
	"\fHourly_units\x12%\n" +
	"\x0etemperature_2m\x18\x02 \x01(\tR\rtemperature2mB;Z9github.com/protocolbuffers/protobuf/examples/go/weatherpbb\x06proto3"

var (
	file_weather_proto_rawDescOnce sync.Once
	file_weather_proto_rawDescData []byte
)

func file_weather_proto_rawDescGZIP() []byte {
	file_weather_proto_rawDescOnce.Do(func() {
		file_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weather_proto_rawDesc), len(file_weather_proto_rawDesc)))
	})
	return file_weather_proto_rawDescData
}

var file_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_weather_proto_goTypes = []any{
	(*Weather)(nil),     // 0: Weather
	(*Hourly)(nil),      // 1: Hourly
	(*HourlyUnits)(nil), // 2: Hourly_units
}
var file_weather_proto_depIdxs = []int32{
	1, // 0: Weather.hourly:type_name -> Hourly
	2, // 1: Weather.hourly_units:type_name -> Hourly_units
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_weather_proto_init() }
func file_weather_proto_init() {
	if File_weather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weather_proto_rawDesc), len(file_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_weather_proto_goTypes,
		DependencyIndexes: file_weather_proto_depIdxs,
		MessageInfos:      file_weather_proto_msgTypes,
	}.Build()
	File_weather_proto = out.File
	file_weather_proto_goTypes = nil
	file_weather_proto_depIdxs = nil
}
